### ISSUE TITLE
Allow for multiple descriptions (due to multiple languages)

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#17]

**Comment by wrygiel** [comment]
In other words, we want all `<description>` elements to have `maxOccurs="unbounded"` and to support the `xml:lang` attribute.

This could potentially break some implementations. (The ones that assumed that there will be only a single element.) If it turns out that it breaks something during tests, then we might add a new element (e.g. `<description2>`), and deprecated the older one.

**Comment by wrygiel** [comment]
I have looked through all `description` elements in the XSD and confirmed that all of them have:

* `minOccurs="0"`
* `maxOccurs="unbounded"`
* `type="PlaintextMultilineStringWithOptionalLang"`
