### ISSUE TITLE
Allow including not-passed LOIs

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#22]
Wojtek check if ECTS can be refused in the XSD if passed is false. Default is true. Very recomended in this version, required in next non-backwards compatible version. Only send false if asked by the client (see issue #23)

**Comment by wrygiel** [comment]
> Wojtek check if ECTS can be refused in the XSD if passed is false. 

Couldn't parse that :) What do you mean?

> Default is true. Very recomended in this version, required in next non-backwards compatible version. Only send false if asked by the client (see issue #23)

Yes. We need to add a new element which indicates if the course (or, in fact, any other LOI) has been "passed" or not. I'm not sure if "passed" is the best term to be used here - it fits the courses, but does it also fit e.g. Degree Programmes?

The default would be `<passed>true</passed>`, because currently (by default) we include only passed courses in the response. **It will also be default true for all other LO types**, which is not really backwards-compatible, because previously it hasn't been stated that ELMO file includes only passed Degree Programmes. We need to state it explicitly and warn all NCP developers who might have assumed otherwise (as far as I know, Poland was among them).

In order to help to clear this confusion we want all NCP developers to explicitly include the `<passed>` element on all LOIs. The element won't be required in the schema, but we want all NCP developers to include it anyway.

**Comment by wrygiel** [comment]
Updated the name to better suit what we need. We don't really care if the course was failed - we care if was passed or not (yet). That's not the same.

Alternatively, we could think about three separate statuses: `passed/failed/in-progress`. I guess it wouldn't be hard for NCP implementers to supply those?

**Comment by wrygiel** [comment]
Staged in `v1.2-preview`. Follow [this thread](https://github.com/emrex-eu/elmo-schemas/issues/37) to see when this is actually released.
