### ISSUE TITLE
Extra EMP parameters: "allowToPickLOIs" and "allowNotPassedLOIs"

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#23]
Extra EMP parameters: "allowToPickCourses" and "allowNotPassedCourses", as described [here](https://github.com/MUCI/emrex-elmo-extensions). The ELMO file would also need to have these values included (so that the reader knows all the details of the mobility).
Polish NCPs already support this feature, but it seems that Poland is not the only country which wants to make use of them (we recently learned that Denmark needs it too).
Italy also (discussion during the Stakeholder forum)

**Comment by wrygiel** [comment]
During the meeting we conclused that these would need to be named differently, because they will refer to all LOIs, not only the Courses. E.g. `allowToPickLOIs` and `allowNotPassedLOIs`.

We also need new elements in the ELMO file which will enable NCP developer to indicate if he honored these new EMP parameters or not. We won't require EMPs to honor them, because we suspect that in some countries this might create legal issues.

**Comment by wrygiel** [comment]
Related: I heard that it is planned to move EMREX specs to GitHub. Is it true?

**Comment by wrygiel** [comment]
We need a way of publishing a "draft" version of these changes, without really modifying the released NCP specs (yet).

**Comment by wrygiel** [comment]
We may also need an extra field in the EMREX registry (to allow institutions to state if they support this new feature or not).

**Comment by geirmv** [comment]
ELMO meeting 15.12.21: Not any interest at the moment to move on with this

**Comment by mirkostanic** [comment]
Closed due to inactivity.
