### ISSUE TITLE
Add language option for all content.

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#24]

**Comment by wrygiel** [comment]
You mean, all `<description>` elements? I guess this is already the case then.

**Comment by wrygiel** [comment]
https://github.com/emrex-eu/elmo-schemas/issues/17

**Comment by wrygiel** [comment]
Clarified by @richared1979: Verify that all titles and descriptions have multiple languages.

**Comment by wrygiel** [comment]
I wonder... Perhaps the original reported has even more elements in mind? E.g. `url` elements? I think this should be clarified.

**Comment by wrygiel** [comment]
Description elements were already verified in https://github.com/emrex-eu/elmo-schemas/issues/17.

I have now verified that all `title` elements have

* `type="TokenWithOptionalLang"`
* `maxOccurs="unbounded"`

So, if this issue is only about the title and description elements, then it can be closed. However I still think you should check with the initial reporter.
