### ISSUE TITLE
Add a way to connect attachment to a specific LOS

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#25]
Add a way to connect attachment to a specific LOS, either thorugh ELMO-ID pointer or the possibility to add attachments straight to LOS.

**Comment by wrygiel** [comment]
During the meeting we (tentatively) concluded, that it will be better (more backward-compatible) to add use references, rather than to move the attachments to LOS/LOI elements.

This relationship is "optional 1 to 1". So, it allows for a single attachment to be connected to a single LOS (or LOI? not sure). The same attachment cannot be connected to a different LOS. Also, the same LOS cannot be connected to a different attachment (?). Richard, confirm if I understand it correctly.

Also, we need to describe what is the purpose of this and how should client developers display it.

Other questions:

* Wouldn't it be safer it we make it "optional many to many"? I guess it might serve more purposes this way.

**Comment by wrygiel** [comment]
@richared1979 please confirm

**Comment by wrygiel** [comment]
We need to confirm with the person who initiated this change.

**Comment by richared** [comment]
Added a suggestion to how this can be implemented, please see https://github.com/emrex-eu/elmo-schemas/tree/issue25

**Comment by janinamincer-daszkiewicz** [comment]
XSD:
enumaration --> enumeration
If the none of the predefined values apply --> If none of the predefined values apply
should be reminde --> should be reminded
that the the number of types --> that the number of types

Otherwise no objections from University of Warsaw (and MUCI).

**Comment by geirmv** [comment]
Adding attachment to specific LOI was introduced with ELMO 1.3
