### ISSUE TITLE
Add "you should ignore unknown types" in description

### ISSUE THREAD

**Issue by emrex-eu** [emrex-eu/elmo-schemas#33]
We should add a general advice to ignore unknow types in the XSD description

**Comment by wrygiel** [comment]
I believe this requires to be explicitly stated directly in certain places. This is implicitly assumed in places where type can be any string. But, for example, in case of LOS type, when it is a strict enumeration, many developers will assume that it won't be extended.

If we really want developers to respect that, then maybe we should allow for LOS `<type>` to be any string? And describe the "currently defined" ones in the annotation?

**Comment by wrygiel** [comment]
TODO: Go through the schema and add this comment whenever applicable.

**Comment by wrygiel** [comment]
I went through the schema and found two enumerations for which this strategy wasn't explicitly specified:

* The newly introduced `status` element. In this case I believe that clients **MAY** assume that it won't change in the future. Adding more `status` values is somewhat inconceivable at this point. If we ever need to add more (why would we?), then a new `status2` element should be added, I think.

* The `level` element, which is [planned to be deprecated](https://github.com/emrex-eu/elmo-schemas/issues/26). Not sure how to deal with that one. Since we want to deprecate it, then perhaps it's okay to use the same strategy as with `status` above?

**Comment by wrygiel** [comment]
* Documented the `status` the way I proposed above.
* Added some docs to the level element warning servers and clients not to use it.

Staged in `v1.2-preview`. Follow [this thread](https://github.com/emrex-eu/elmo-schemas/issues/37) to see when this is actually released.
