### ISSUE TITLE
Absence of LearningOportunityInstance

### ISSUE THREAD

**Issue by zak-michal** [emrex-eu/elmo-schemas#40]
It is not obvious how to deal with absence of learnigOportunitySpecification/Instance elements in elmo file.

Comment in elmo schema says:

> Additional note for client implementers:
> 
> Please note that it is ALLOWED for the report to contain zero
> learningOpportunitySpecifications. This may happen for example when the student
> has unchecked all the courses during the EMREX NCP export process. This is NOT an
> error, and it should NOT trigger the "manual verification" process on your
> part (you might want to show a warning though).

Dutch NCP serves only learner, issuer, and pdf attachments in elmo file. We should decide how to recognize following situations:
- learner selected no courses to export
- NCP does not serve any coures details

**Comment by richared1979** [comment]
Currently, in Norway at least, we depend on having LOS present, but that is something we should remedy.

If there are no LOS, the attached PDF should be stored in the system somehow and a notification should be sent to the student administration that there needs to be some sort of manual work to be done to transfer the data into the system, like you would do with paper.

I would say the same would apply in the absence of LOI, because you really don't have ant student-specific data and some sort of manual work is required.

**Comment by wrygiel** [comment]
> If there are no LOS, the attached PDF should be stored in the system somehow and a notification should be sent to the student administration that there needs to be some sort of manual work to be done to transfer the data into the system, like you would do with paper.

This PDF *also* can be empty (because the student might have simply selected zero courses). If I understand the problem right, the best solution would be to add a new element saying "Sorry, I don't support LOS/LOI elements, but the attached PDF *does* contain those".

**Comment by geirmv** [comment]
Close this issue, this hasn't come up later after implementation of the DUO NCP
